version: 0.2

env:
  variables:
    flag: "-3"

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - |
        if [ "$flag" -gt "0" ]; then
          echo "The conditional works"
        else
          echo "The conditional go for the else"
        fi
artifacts:
  files:
    - target/messageUtil-1.0.jar